Upgrade Xtext dependency and Gradle Xtext plugin version
The previous ones depended on a SNAPSHOT version which changed causing
errors in the Gradle build such as:

Execution failed for task ':trainbenchmark-format-emf-model:generateXtext'.
> java.lang.NoSuchMethodError: org.eclipse.emf.ecore.xcore.parser.antlr.internal.InternalXcoreParser.setWithLastConsumed(Lorg/eclipse/emf/ecore/EObject;Ljava/lang/String;ZLjava/lang/String;)V